### ISSUE TITLE
[BUG] Could not update/delete jobs/tagrets in CLI when logged in as github user with admin role

### ISSUE THREAD

**Issue by xiujiao** [starkandwayne/shield#501] opened 2019-04-25 14:51 UTC
The process is that we logged in as GitHub user, the role is an admin in the tenant, we created jobs and targets in web UI. 

Then we log in as github user in CLI, try to update or delete a job, it responded successfully, but the job did not get updated or deleted as expected

then we logged in as `admin` and password, assign the admin role in the gui, then we also logged in shield through CLI using `admin` and password,  we can successfully delete or update jobs

then we logged out as `admin` user, logged in  as github user, now we can update and delete jobs now

both admin and github user has admin role assigned in the tenant

**Comment by jhunt** [comment] 2019-05-02 13:56
Were you able to capture HTTP trace/debugging output from the CLI?  That would be most helpful in tracking down the root cause of this issue.

**Comment by xiujiao** [comment] 2019-05-02 14:24
@jhunt I was not able to do that yet since my github oauth did not work. I will come back to it later
github oauth gives me 501

**Comment by xiujiao** [comment] 2019-05-03 14:30
I could not reproduce the bug in our lab, I used the same version of the kit and GitHub OAuth. Everything worked for me. The main differences from the env that has the issue are 1) proxy 2) enterprise GitHub instead of an org in GitHub

**Comment by jhunt** [comment] 2019-05-14 12:42
Closing this as we could not reproduce the original aberrant behavior.  Please re-open if you find a way to reproduce.  Thanks!

**Closed** 2019-05-14 12:42 UTC
Labels: no-repro
