### ISSUE TITLE
Shield Web UI Needs Feedback for Initiating Restore

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/shield#176] opened 2016-06-06 19:21 UTC
The button/page doesn't do anything when you click the restore. Well... except, initiate the restore. Leads to: 
<img width="1433" alt="restores" src="https://cloud.githubusercontent.com/assets/12000017/15834613/43ef348a-2bfa-11e6-9777-1a60fa20dcb1.png">

**Comment by jhunt** [comment] 2016-06-06 19:49
Duplicate of #137

**Closed by jhunt** 2016-06-06 19:49 UTC
