### ISSUE TITLE
"Every-x-hours" sets "0 backups for x days"

### ISSUE THREAD

**Issue by jordanbcooper** [starkandwayne/shield#460] opened 2018-10-08 15:49 UTC
When setting "every x hours" (in my case, via import) backup jobs specify "keep 0 backups (x days)"

**Comment by defhand** [comment] 2019-03-14 00:42
@jhunt Any reccomendations here?

**Comment by jhunt** [comment] 2019-03-14 15:39
I just ran some tests in our lab, running 8.0.17, and here's what I found.

1. The timespec `every 4 hours` is a syntax error.
2. The timespec `every 4 hours at 12:15am` is also a syntax error.
3. The timespec `every 4 hours from 12:15am` is _not_ a syntax error.

When you configure a backup job via the web UI, the every-x-hours flavor of scheduling comes out in text(timespec) as `every X hours from HH:MMam`

Here's a screenshot!

<img width="819" alt="Every X Hours (bottom schedule)" src="https://user-images.githubusercontent.com/20047/54370286-bbe0aa80-464d-11e9-9c35-4c483c755f64.png">

I'm curious if we are dealing with an edge case I just can't find, or if the import process is incorrectly parsing, or just not validating the input schedule timespec.

@jordanbcooper  / @defhand what timespec strings are you sending up to SHIELD to evoke this behavior?

**Comment by jordanbcooper** [comment] 2019-03-15 21:31
Looks like i'm sending 

`    jobs:
    - name:  job-name
      policy: Long-Term
      storage: S3 - database
      when: every 3 hours from 12:00AM`

**Comment by jordanbcooper** [comment] 2019-03-15 21:46
Er, that didn't fix it. My polices are Short-Term and Long-Term and are applied to each job accordingly. Strangely, my "daily 4am" job says "keep 90 backups (90 days)"

**Comment by jhunt** [comment] 2019-03-15 23:28
Previously, on _"Every-x-hours" sets "0 backups for x days"_:

I originally thought we were dealing with bad validation on the import command / API handler, so I tried this import file:

```
core: http://127.0.0.1:8180
token: 353425ce-ccfe-4e10-8439-f3dce810dc48

tenants:
  - name: Acme, Inc.
    systems:
      - name:    'Jordan (at)'
        summary: A test system for generating lots of web UI output and pushing the limits of the web UI
        agent:   vault:5444
        plugin:  fs
        config:
          base_dir: /tmp
        jobs:
          - name:     Fast AT
            when:     every 3 hours at 12:05am
            paused:   yes
            storage:  S3
            policy:   Long-Term
```

when I ran that, however, I got this:

```
Connecting to http://127.0.0.1:8180
Importing Users...

Importing Shared Storage...

Importing Retention Policy Templates...

Importing Tenants...
importing tenant Acme, Inc....
Acme, Inc.> inviting local users...
Acme, Inc.> importing cloud storage systems...
Acme, Inc.> importing retention policies...
Acme, Inc.> importing data systems...
Acme, Inc.> creating data system Jordan (at), using the fs plugin
Acme, Inc. :: Jordan (at)> creating Fast AT job, running at every 3 hours at 12:05am
!!! x.yml: failed to configure job 'Fast AT' of data system 'Jordan (at)' for tenant 'Acme, Inc.': Invalid or malformed SHIELD Job Schedule 'every 3 hours at 12:05am' (server-side error: There was a syntax error in your SHIELD timespec 'every 3 hours at 12:05am')
```

which disqualifies _that_ theory.

so instead, I changed the _at_ to a _from_ (a valid timespec) and got this:

```
Importing Retention Policy Templates...

Importing Tenants...
importing tenant Acme, Inc....
Acme, Inc.> inviting local users...
Acme, Inc.> importing cloud storage systems...
Acme, Inc.> importing retention policies...
Acme, Inc.> importing data systems...
Acme, Inc.> creating data system Jordan (from), using the fs plugin
Acme, Inc. :: Jordan (from)> creating Fast FROM job, running at every 3 hours from 12:05am
```

From the web UI (since this version of SHIELD doesn't show the retention details on the CLI, apparently), I get this:

<img width="812" alt="Screen Shot 2019-03-15 at 7 24 58 PM" src="https://user-images.githubusercontent.com/20047/54466822-0bab9880-4758-11e9-88b2-3f4366c613dc.png">

(this was all on latest master, commit 2163220, which for all intents and purposes is 8.0.19)

@jordanbcooper what version of SHIELD are you seeing this in?

**Comment by jhunt** [comment] 2019-03-29 12:05
I _believe_ this has been fixed in the massive changeset coming next week, in 8.1.  I'm going to put tag this issue as such, but leave it open.

**Comment by jordanbcooper** [comment] 2019-04-01 14:14
Thanks @jhunt !

**Comment by jhunt** [comment] 2019-04-03 12:25
SHIELD 8.1.0 is out! https://github.com/starkandwayne/shield/releases/tag/v8.1.0

**Comment by jhunt** [comment] 2019-04-05 11:40
Found this again this morning. 😞 

<img width="864" alt="Screen Shot 2019-04-05 at 7 39 30 AM" src="https://user-images.githubusercontent.com/20047/55625196-10bba080-5776-11e9-84b3-132e51c64469.png">

(reproducible by running the Docker Compose demo that comes with SHIELD)

Will continue to look into this.

**Comment by jhunt** [comment] 2019-05-15 14:14
Did some digging into this, since the Docker system is still exhibiting this behavior.  Doing so, I found the following disparity in API:

in `POST /v2/tenants/:uuid/jobs`:

```
        job, err := c.db.CreateJob(&db.Job{
            TenantUUID: r.Args[1],
            Name:       in.Name,
            Summary:    in.Summary,
            Schedule:   in.Schedule,
            KeepDays:   keepdays,
            KeepN:      keepn,
            Paused:     in.Paused,
            StoreUUID:  in.Store,
            TargetUUID: in.Target,
            FixedKey:   in.FixedKey,
        })
```

but in `POST /v2/tenants/:uuid/systems`:

```
        job, err := c.db.CreateJob(&db.Job{
            TenantUUID: r.Args[1],
            Name:       in.Job.Name,
            Schedule:   in.Job.Schedule,
            KeepDays:   in.Job.KeepDays,
            Paused:     in.Job.Paused,
            StoreUUID:  store.UUID,
            TargetUUID: target.UUID,
            FixedKey:   in.Job.FixedKey,
        })
```

It looks like the systems-oriented endpoint (vs. the CLI-specific job-oriented endpoint) is _not_ setting `KeepN`.

If my theory is correct, and this disparity is to blame, then any automated CLI-based testing will not be able to reproduce this issue, but setting things up via the Web UI will always exhibit the incorrect behavior.

**Comment by jhunt** [comment] 2019-05-15 14:28
BAM! :boom:

Verified.

<img width="801" alt="Screen Shot 2019-05-15 at 10 24 07 AM" src="https://user-images.githubusercontent.com/20047/57783209-be1dbe80-76fb-11e9-8a47-33bf3292ebee.png">

The top job, "Hourly" was created via CLI stuff in `dev-setup`.  The bottom job, "web-ui-created-460" was created via the Web UI.

**Comment by jordanbcooper** [comment] 2019-05-15 14:44
Just wanted to say that everything I configured on my SHIELD instance is via CLI, not via the web ui

**Comment by jhunt** [comment] 2019-05-15 14:51
Good to know!

I will try an import, since the testdev env (source of the "Hourly" job, above) uses `shield create-job`, not `shield-import`

**Comment by jhunt** [comment] 2019-05-15 15:37
Importing seems to work as well:

<img width="781" alt="Screen Shot 2019-05-15 at 11 35 25 AM" src="https://user-images.githubusercontent.com/20047/57788732-9c293980-7705-11e9-9673-3b0ea602dba2.png">

using the following import YAML file:

```
tenants:
  - name: Acme, Inc.
    systems:
      - name:    'Schedule Test'
        summary: A test system for generating lots of web UI output and pushing the limits of the web UI
        agent:   vault:5444
        plugin:  fs
        config:
          base_dir: /tmp
        jobs:
          - name:     Minutely
            when:     every minute
            paused:   yes
            storage:  Globus
            retain:   1d

          - name:     Hourly
            when:     hourly at x:15
            paused:   yes
            storage:  Globus
            retain:   1d

          - name:     Issue 460
            when:     every 3 hours from 12:00AM
            paused:   yes
            storage:  Globus
            retain:   2d

          - name:     Semi-Daily
            when:     every 8 hours from 04:15am
            paused:   yes
            storage:  Globus
            retain:   2d

          - name:     Daily
            when:     daily at 3:25am
            paused:   yes
            storage:  Globus
            retain:   4d

          - name:     Daily 2
            when:     daily 3:45am
            paused:   yes
            storage:  Globus
            retain:   4d

          - name:     Weekly
            when:     tuesdays at 5:55pm
            paused:   yes
            storage:  Globus
            retain:   6w
```

@jordanbcooper can you try 8.1.x (both a fresh instance and an upgrade) and see if the import works better?  The Web UI fix is on master, so you won't be able to deploy that one quite yet...

**Comment by jhunt** [comment] 2019-05-15 15:57
The `fix-460` branch has a fix staged for this, pending feedback from @jordanbcooper before submitting a full PR

**Comment by jordanbcooper** [comment] 2019-05-15 16:32
After upgrading to 8.1.0 and updating my CLI (also adding "retain" to my import yamls) issue is resolved

**Comment by jhunt** [comment] 2019-05-15 16:35
Excellent.  We will merge the Web UI vector fix.  Thanks!

**Closed** 2019-05-15 16:35 UTC
Labels: bug
