### ISSUE TITLE
fs plugin fails on shield core db-journal file

### ISSUE THREAD

**Issue by ChrisMcGowan** [starkandwayne/shield#440] opened 2018-08-02 15:20 UTC
Using fs plugin to back shield core with local shield agent fails intermittently on the fs walk of `/var/vcap/store/shield` where the backup then tries to backup `/var/vcap/store/shield/shield.db-journal`

Adding the `exclude=*.db-journal` to the job does not resolve the issue.

**Comment by jhunt** [comment] 2018-08-03 13:42
The root of the problem is that the `*.db-journal` file is pretty short-lived.  It pops into existence during SQL execution, as a journal to protect against failure and avoid data corruption, while maintaining ACID, so it's hard to force it to exist.  If it always existed, it would be fine, but the walk code doesn't seem to honor the exclusion; that appears to only be in effect when figuring out what to put _into_ the archive tarball.

There's two fixes needed here (I think) --

1. Build a new `shield` plugin that doesn't rely on filesystem backups
2. Make the walk code better (if that's possible) so that it doesn't mind files disappearing.

(2) might require that we write our own file tree traversal logic, since I believe it's currently all hidden inside of Go standard libraries.

**Comment by jhunt** [comment] 2019-03-28 12:52
Handling the specific file-not-found error turned out to be easier than I had originally anticipated, so that is the approach we opted to take.  This should be fixed in the 8.1.0 release, which should be out the door by next week (just in time for CF Summit Philly!)

**Comment by jhunt** [comment] 2019-04-03 12:26
Fixed in v8.1.0 and above, with the new `strict_mode` setting for the `fs` plugin.  Setting that to `no` (or false, or 0 or other YAML falsey values) will stop the filepath walker from choking on stat errors related to "the file's gone missing since we listed the directory".  This is also the new default behavior.

**Closed by jhunt** 2019-04-03 12:26 UTC
Labels: fixed-pending
